[package]
name = "kito"
description = "A web framework written in Rust for TypeScript"
version = "0.1.0"
authors = ["Nehuén <https://github.com/nehu3n>"]
repository = "https://github.com/nehu3n/kito"
license = "MIT"
readme = "README.md"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
actix-web = "4"